
//Font Generated by MikroElektronika GLCD Font Creator 1.2.0.0
//MikroElektrnika 2011 
//http://www.mikroe.com 

//GLCD FontName : Noto_Sans_Mono_Blk52x71
//GLCD FontSize : 52 x 71

#include "gfx_mono.h"
#include "gfx_mono_text.h"

extern struct font noto_sans_mono_blk_52x71;
